CREATE TABLE CHARACTER(
      ID INT AUTO_INCREMENT,
      NAME VARCHAR(255),
      CLASS VARCHAR(225),
      RACE VARCHAR(225),
      SIZE VARCHAR(225),
      GENDER VARCHAR(225),
      HOME_WORLD VARCHAR(225),
      SPEED INT,
      ALIGNMENT VARCHAR(225),
      DEITY VARCHAR(225)
);

